BiasedBalance.Planet_Pool = {
    "pluto",
    "mercury",
    "uranus",
    "venus",
    "saturn",
    "jupiter",
    "earth",
    "mars",
    "neptune",
--  "planet_x",
--  "ceres",
--  "eris"
}

BiasedBalance.Hone_Tag_Editions = {
    "e_foil",
    "e_holo",
    "e_polychrome"
}

BiasedBalance.Common_Jokers = {
-- ||   Tweaks    ||
    "abstract",
    "banner",
    "blue_joker",
    "bootstrap",
    "business",
    "castle",
    "chaos",
    "clever",
    "cloud_9",
    "crafty",
    "crazy",
    "credit_card",
    "delayed_grat",
    "devious",
    "droll",
    "drunknard",
    "egg",
    "even_steven",
    "faceless_joker",
    "fortune_teller",
    "flash",
    "flower_pot",
    "gluttenous_joker",
    "golden",
    "greedy_joker",
    "green_joker",
    "gros_michel",
    "half",
    "hallucination",
    "hanging_chad",
    "hiker",
    "ice_cream",
    "joker",
    "jolly",
    "juggler",
    "lusty_joker",
    "mad",
    "mail",
    "misprint",
    "mystic_summit",
    "odd_todd",
    "popcorn",
    "raised_fist",
    "red_card",
    "reserved_parking",
    "ride_the_bus",
    "riff_raff",
    "runner",
    "scary_face",
    "scholar",
    "shoot_the_moon",
    "sly",
    "space",
    "splash",
    "square",
    "supernova",
    "swashbuckler",
    "ticket",
    "todo_list",
    "wily",
    "wrathful_joker",
    "zany"
-- ||   Adds    ||
    -- "biasedBalance_ballerina",
    -- "biasedBalance_caviar",
    -- "biasedBalance_conspiracy",
    -- "biasedBalance_discounted_joker",
    -- "biasedBalance_eldritch_joker",
    -- "biasedBalance_electic_joker",
    -- "biasedBalance_everhungry_joker",
    -- "biasedBalance_hypernova",
    -- "biasedBalance_impatient_joker",
    -- "biasedBalance_jokerdex",
    -- "biasedBalance_missing_piece",
    -- "biasedBalance_mystery_box",
    -- "biasedBalance_ominous_concoction",
    -- "biasedBalance_peafowl",
    -- "biasedBalance_pitiful_joker",
    -- "biasedBalance_platnium_joker",
    -- "biasedBalance_practical_perfectionist",
    -- "biasedBalance_short_fuse",
    -- "biasedBalance_smurf",
    -- "biasedBalance_terrace_garden",
    -- "biasedBalance_wallpaper",
    -- "biasedBalance_wysteria_joker"
}

BiasedBalance.Rare_Jokers = {
-- ||   Tweaks    ||
    "ancient",
    "baron",
    "baseball",
    "blueprint",
    "brainstorm",
    "burnt",
    "card_sharp",
    "dna",
    "duo",
    "family",
    "hologram",
    "invisible",
    "obelisk",
    "order",
    "stuntman",
    "tribe",
    "trio",
    "vagabond",
    "wee"
-- ||   Adds    ||
    -- "biasedBalance_death_and_taxes",
    -- "biasedBalance_esteemed_audience",
    -- "biasedBalance_light_in_the_tunnel",
    -- "biasedBalance_opportunity_cost",
    -- "biasedBalance_prehistoric_joker",
    -- "biasedBalance_propitous_joker",
    -- "biasedBalance_shapeshifter",
    -- "biasedBalance_singularity",
    -- "biasedBalance_spice",
    -- "biasedBalance_velvet_choker",
    -- "biasedBalance_yodeller",
}

BiasedBalance.Legendary_Jokers = {
-- ||   Tweaks    ||
    "canio",
    "chicot",
    "perkeo",
    "triboulet",
    "yorick"
-- ||   Adds    ||
    -- "biasedBalance_",
}

BiasedBalance.Tarots = {
    "fool",
    "magician",
    "high_priestess",
    "empress",
    "emperor",
    "heirophant",
    "lovers",
    "chariot",
    "justice",
    "hermit",
    "wheel_of_fortune",
    "strength",
    "hanged_man",
    "death",
    "temperance",
    "devil",
    "tower",
    "star",
    "moon",
    "sun",
    "judgement",
    "world"
}

BiasedBalance.Spectrals = {
    "familiar",
    "incantation",
    "tailsman",
    "aura",
    "wraith",
    "sigil",
    "ouija",
    "ectoplasm",
    "immolate",
    "ankh",
    "deja_vu",
    "hex",
    "trance",
    "medium",
    "cryptid",
    "biasedBalance_Conjuration",
    "biasedBalance_Stain",
    "biasedBalance_Crossroads",
    "biasedBalance_Awakening",
    "biasedBalance_Sacrifice", 
}

BiasedBalance.Poker_Hands = {
    "Straight Flush",
    "Four of a Kind",
    "Full House",
    "Flush",
    "Straight",
    "Three of a Kind",
    "Two Pair",
    "Pair",
    "High Card"
}

--BiasedBalance.Utility_Jokers {
    
--}