BiasedBalance.Planet_Pool = {
    "pluto",
    "mercury",
    "uranus",
    "venus",
    "saturn",
    "jupiter",
    "earth",
    "mars",
    "neptune",
--  "planet_x",
--  "ceres",
--  "eris"
}

BiasedBalance.Hone_Tag_Editions = {
    "e_foil",
    "e_holo",
    "e_polychrome"
}

BiasedBalance.Common_Jokers = {
    "joker",
    "greedy_joker",
    "lusty_joker",
    "wrathful_joker",
    "gluttonous_joker",
    "crazy_joker",
    "droll_joker",
    "devious_joker",
    "crafty_joker",
    "banner",
    "scary_face",
    "ticket",
    "space",
    "hiker",
    "erosion",
    "to_the_moon",
    "spare_trousers",
    "flower_pot",
    "bootstraps",
    "todo_list",
    "biasedBalance_PitifulJoker",
    "biasedBalance_Jumbo",
    "biasedBalance_Caviar",
    "biasedBalance_Impatient",
    "biasedBalance_Jokester",
}

BiasedBalance.Rare_Jokers = {
    "vagabond",
    "invisible",
    "tribe",
    "card_sharp",
    "dna",
    "baron",
    "obelisk",
    "baseball",
    "blueprint",
    "wee_joker",
    "duo",
    "family",
    "order",
    "stuntman",
    "brainstorm",
    "drivers_license",
    "burnt_joker",
    "biasedBalance_Rivals",
    "biasedBalance_BluntedImpact",
    "biasedBalance_DeathAndTaxes",
    "biasedBalance_FlavourfulJoker",
    "biasedBalance_MelancholicJoker",
    "biasedBalance_BrashGambler",
    "biasedBalance_Bookworm",
    "biasedBalance_Parvenu",
    "biasedBalance_Skipper",
    "biasedBalance_Minstrel",
}

BiasedBalance.Legendary_Jokers = {
    "perkeo",
    "canio",
    "yorick",
    "triboulet",
    "chicot"
}

BiasedBalance.Tarots = {
    "fool",
    "magician",
    "high_priestess",
    "empress",
    "emperor",
    "hierophant",
    "lovers",
    "chariot",
    "justice",
    "hermit",
    "wheel_of_fortune",
    "strength",
    "hanged_man",
    "death",
    "temperance",
    "devil",
    "tower",
    "star",
    "moon",
    "sun",
    "judgement",
    "world"
}

BiasedBalance.Spectrals = {
    "familiar",
    "incantation",
    "tailsman",
    "aura",
    "wraith",
    "sigil",
    "ouija",
    "ectoplasm",
    "immolate",
    "ankh",
    "deja_vu",
    "hex",
    "trance",
    "medium",
    "cryptid",
    "biasedBalance_Conjuration",
    "biasedBalance_Stain",
    "biasedBalance_Crossroads",
    "biasedBalance_Awakening",
    "biasedBalance_Sacrifice", 
}